services:
  - type: web
    name: fake_tron_node
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:443 fake_tron_node:app --certfile cert.pem --keyfile key.pem
    envVars:
      - key: TRONGRID_API_KEY
        value: "123e4567-e89b-12d3-a456-426614174000"
      - key: PROXY_ADDRESS
        value: "TRu5tU5DT..."
  - type: web
    name: metadata_server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:443 metadata_server:app --certfile cert.pem --keyfile key.pem
    envVars:
      - key: TRONGRID_API_KEY
        value: "fake-api-key-1234567890"
      - key: PROXY_ADDRESS
        value: "TRu5tU5DT..."
  - type: web
    name: tw_exploit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:443 tw_exploit:app --certfile cert.pem --keyfile key.pem
    envVars:
      - key: TRONGRID_API_KEY
        value: "fake-api-key-1234567890"
      - key: PROXY_ADDRESS
        value: "TRu5tU5DT..."
  - type: web
    name: event_sync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:443 event_sync:app --certfile cert.pem --keyfile key.pem
    envVars:
      - key: TRONGRID_API_KEY
        value: "fake-api-key-1234567890"
      - key: PROXY_ADDRESS
        value: "TRu5tU5DT..."
      - key: PRIVATE_KEY
        value: "a1b2c3..."
      - key: IMPLEMENTATION_ADDRESS
        value: "TNFUSK7N1HpTe4ex6PtSurZnohvCmX2wA3"
  - type: web
    name: auto_sync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:443 auto_sync:app --certfile cert.pem --keyfile key.pem
    envVars:
      - key: TRONGRID_API_KEY
        value: "fake-api-key-1234567890"
      - key: PROXY_ADDRESS
        value: "TRu5tU5DT..."
      - key: PRIVATE_KEY
        value: "a1b2c3..."
      - key: IMPLEMENTATION_ADDRESS
        value: "TNFUSK7N1HpTe4ex6PtSurZnohvCmX2wA3"
  - type: static
    name: static_files
    buildCommand: ""
    staticPublishPath: static
    envVars:
      - key: TOKEN_METADATA_PATH
        value: "/tokens/token_metadata.json"