services:
  - type: web
    name: new-token-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn metadata_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: API_KEY
        value: "SiyahSancak0258-MY-TOKEN-SiyahSancak0258"  # Kendi anahtarınız
      - key: ETHERSCAN_API_KEY
        value: "E1MD7M2UGT1ZTTVX55JR6SVYKSBVA2EKCB"  # Kendi Etherscan anahtarınız
      - key: CONTRACT_ADDRESS
        value: "0xDAC17f2a9b484780B9e109E003F7BB78B1C54A29"  # ADIM 7’den güncelleyin
      - key: REDIS_URL
        fromService:
          type: redis
          name: usdt-api-redis
          property: connectionString
redis:
  - name: usdt-api-redis
    plan: free